name: vipa
description: "vipa"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  flutter_tts: ^4.2.5
  remixicon: ^4.9.1
  provider: ^6.1.5+1
  dio: ^5.9.2
  google_sign_in: ^7.2.0
  kakao_flutter_sdk: ^2.0.0+1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  get: ^4.7.3
  get_storage: ^2.1.1
  intl: ^0.20.2
  record: ^6.2.0
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  screenshot: ^3.0.0
  share_plus: ^13.1.0
  pdf: ^3.12.0
  printing: ^5.14.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicons.png" #
  min_sdk_android: 21
